### ISSUE TITLE
运行脚本dnf安装失败，但是手动执行发现dnf已经安装

### ISSUE THREAD

**Issue by YukishiroKarin** [kirin10000/Xray-script#196]
报错
Traceback (most recent call last):
  File "/bin/dnf", line 58, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 179, in user_main
    errcode = main(args)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 64, in main
    return _main(base, args, cli_class, option_parser_class)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 99, in _main
    return cli_run(cli, base)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 115, in cli_run
    cli.run()
  File "/usr/lib/python2.7/site-packages/dnf/cli/cli.py", line 1125, in run
    return self.command.run()
  File "/usr/lib/python2.7/site-packages/dnf/cli/commands/mark.py", line 89, in run
    rpmdb_version = self.sack._rpmdb_version()
AttributeError: 'MarkCommand' object has no attribute 'sack'
尝试yum安装和手动执行命令，发现dnf已经安装并且可正常执行
系统Cenotos7.9

**Comment by kirin10000** [comment]
1. 日志不够多，使用`bash -x Xray-REALITY+Web.sh`运行脚本，附上完整日志。
2. 运行 type -P dnf 试试
3. 运行`yum update`，然后`yum upgrade`试试

**Comment by myworksfun** [comment]
r如下为centos7.9 报错的info.
```
# bash -x Xray-REALITY+Web.sh
+ unset arch
+ unset distro
+ unset distro_like
+ unset system_version
+ unset pkg
+ unset nproc
+ nginx_version=nginx-1.25.1
+ openssl_version=openssl-openssl-3.1.1
+ nginx_prefix=/usr/local/nginx
+ nginx_config=/usr/local/nginx/conf.d/xray.conf
+ nginx_service=/etc/systemd/system/nginx.service
+ php_version=php-8.2.8
+ php_prefix=/usr/local/php
+ php_service=/etc/systemd/system/php-fpm.service
+ cloudreve_version=3.8.0
+ nextcloud_url=https://download.nextcloud.com/server/releases/nextcloud-27.0.0.tar.bz2
+ xray_config=/usr/local/etc/xray/config.json
+ temp_dir=/temp_install_xray_reality_web
+ unset is_installed
+ unset xray_is_installed
+ unset nginx_is_installed
+ unset php_is_installed
+ unset domain_list
+ unset true_domain_list
+ unset domain_config_list
+ unset pretend_list
+ unset pretend_redirect_list
+ unset pretend_redirect_index_list
+ unset protocol_1
+ unset protocol_2
+ unset protocol_3
+ unset xid_1
+ unset reality_public_key
+ unset reality_private_key
+ unset xid_2
+ unset serviceName
+ unset xid_3
+ unset path
+ using_swap_now=0
+ update=0
+ in_install_update_xray_reality_web=0
+ script_url=https://github.com/kirin10000/Xray-script/raw/main/Xray-REALITY+Web.sh
+ check_and_get_system_info
+ check_base_command
+ hash -r
+ local i
+ temp_command_list=('bash' 'sh' 'command' 'type' 'hash' 'install' 'true' 'false' 'exit' 'echo' 'test' 'sort' 'sed' 'awk' 'grep' 'cut' 'cd' 'rm' 'cp' 'mv' 'head' 'tail' 'uname' 'tr' 'md5sum' 'cat' 'find' 'wc' 'ls' 'mktemp' 'swapon' 'swapoff' 'mkswap' 'chmod' 'chown' 'chgrp' 'export' 'tar' 'gzip' 'mkdir' 'arch' 'uniq' 'dd' 'env' 'mapfile' 'nproc' 'sleep' 'read')
+ local temp_command_list
+ for i in '"${temp_command_list[@]}"'
+ command -V bash
+ for i in '"${temp_command_list[@]}"'
+ command -V sh
+ for i in '"${temp_command_list[@]}"'
+ command -V command
+ for i in '"${temp_command_list[@]}"'
+ command -V type
+ for i in '"${temp_command_list[@]}"'
+ command -V hash
+ for i in '"${temp_command_list[@]}"'
+ command -V install
+ for i in '"${temp_command_list[@]}"'
+ command -V true
+ for i in '"${temp_command_list[@]}"'
+ command -V false
+ for i in '"${temp_command_list[@]}"'
+ command -V exit
+ for i in '"${temp_command_list[@]}"'
+ command -V echo
+ for i in '"${temp_command_list[@]}"'
+ command -V test
+ for i in '"${temp_command_list[@]}"'
+ command -V sort
+ for i in '"${temp_command_list[@]}"'
+ command -V sed
+ for i in '"${temp_command_list[@]}"'
+ command -V awk
+ for i in '"${temp_command_list[@]}"'
+ command -V grep
+ for i in '"${temp_command_list[@]}"'
+ command -V cut
+ for i in '"${temp_command_list[@]}"'
+ command -V cd
+ for i in '"${temp_command_list[@]}"'
+ command -V rm
+ for i in '"${temp_command_list[@]}"'
+ command -V cp
+ for i in '"${temp_command_list[@]}"'
+ command -V mv
+ for i in '"${temp_command_list[@]}"'
+ command -V head
+ for i in '"${temp_command_list[@]}"'
+ command -V tail
+ for i in '"${temp_command_list[@]}"'
+ command -V uname
+ for i in '"${temp_command_list[@]}"'
+ command -V tr
+ for i in '"${temp_command_list[@]}"'
+ command -V md5sum
+ for i in '"${temp_command_list[@]}"'
+ command -V cat
+ for i in '"${temp_command_list[@]}"'
+ command -V find
+ for i in '"${temp_command_list[@]}"'
+ command -V wc
+ for i in '"${temp_command_list[@]}"'
+ command -V ls
+ for i in '"${temp_command_list[@]}"'
+ command -V mktemp
+ for i in '"${temp_command_list[@]}"'
+ command -V swapon
+ for i in '"${temp_command_list[@]}"'
+ command -V swapoff
+ for i in '"${temp_command_list[@]}"'
+ command -V mkswap
+ for i in '"${temp_command_list[@]}"'
+ command -V chmod
+ for i in '"${temp_command_list[@]}"'
+ command -V chown
+ for i in '"${temp_command_list[@]}"'
+ command -V chgrp
+ for i in '"${temp_command_list[@]}"'
+ command -V export
+ for i in '"${temp_command_list[@]}"'
+ command -V tar
+ for i in '"${temp_command_list[@]}"'
+ command -V gzip
+ for i in '"${temp_command_list[@]}"'
+ command -V mkdir
+ for i in '"${temp_command_list[@]}"'
+ command -V arch
+ for i in '"${temp_command_list[@]}"'
+ command -V uniq
+ for i in '"${temp_command_list[@]}"'
+ command -V dd
+ for i in '"${temp_command_list[@]}"'
+ command -V env
+ for i in '"${temp_command_list[@]}"'
+ command -V mapfile
+ for i in '"${temp_command_list[@]}"'
+ command -V nproc
+ for i in '"${temp_command_list[@]}"'
+ command -V sleep
+ for i in '"${temp_command_list[@]}"'
+ command -V read
+ temp_command_list=('rm' 'mkdir' 'chmod' 'chown')
+ for i in '"${temp_command_list[@]}"'
++ type -P rm
+ '[' -z /usr/bin/rm ']'
+ for i in '"${temp_command_list[@]}"'
++ type -P mkdir
+ '[' -z /usr/bin/mkdir ']'
+ for i in '"${temp_command_list[@]}"'
++ type -P chmod
+ '[' -z /usr/bin/chmod ']'
+ for i in '"${temp_command_list[@]}"'
++ type -P chown
+ '[' -z /usr/bin/chown ']'
+ '[' 0 '!=' 0 ']'
+ check_sudo
+ '[' '' ']'
+ return 0
+ [[ ! -f /etc/os-release ]]
+ [[ -d /run ]]
+ [[ -f /.dockerenv ]]
+ grep -q 'docker\|lxc' /proc/1/cgroup
+ [[ -d /run/systemd/system ]]
+ true
++ type -P apt
+ '[' -n '' ']'
++ type -P apt-get
+ '[' -n '' ']'
++ type -P dnf
+ '[' -n /usr/bin/dnf ']'
+ distro_like=rhel
++ type -P dnf
+ '[' -n /usr/bin/dnf ']'
+ pkg=dnf
++ type -P rpm
+ '[' -z /usr/bin/rpm ']'
+ grep -q '\-\-setopt'
+ dnf --help
+ grep -q '\-\-disablerepo'
+ dnf --help
+ grep -q '\-\-enablerepo'
+ dnf --help
+ '[' dnf '!=' dnf ']'
+ local temp_str
+ local id
++ cut -d = -f 2-
++ grep '^[ 	]*ID[ 	]*=' /etc/os-release
+ temp_str='"centos"'
+ trim_str
+ [[ "centos" =~ " ]]
+ [[ "centos" =~ ^".*"$ ]]
+ temp_str='centos"'
+ temp_str=centos
+ id=centos
+ local name
++ cut -d = -f 2-
++ grep '^[ 	]*NAME[ 	]*=' /etc/os-release
+ temp_str='"CentOS Linux"'
+ trim_str
+ [[ "CentOS Linux" =~ " ]]
+ [[ "CentOS Linux" =~ ^".*"$ ]]
+ temp_str='CentOS Linux"'
+ temp_str='CentOS Linux'
+ name='CentOS Linux'
+ '[' -z centos ']'
+ '[' -z 'CentOS Linux' ']'
+ :
+ grep -qiw ubuntu
+ grep -qiw debian
+ grep -qiw fedora
+ grep -qiw centos
+ grep -qiw centos
+ '[' rhel == rhel ']'
+ grep -qiw stream
+ distro=centos
+ break
++ cut -d = -f 2-
++ grep '^[ 	]*VERSION_ID[ 	]*=' /etc/os-release
+ temp_str='"7"'
+ trim_str
+ [[ "7" =~ " ]]
+ [[ "7" =~ ^".*"$ ]]
+ temp_str='7"'
+ temp_str=7
+ system_version=7
+ case "$(arch)" in
++ arch
+ arch=amd64
++ nproc
+ nproc=1
+ [[ 1 =~ ^(((-|)[1-9][0-9]*)|0)$ ]]
+ '[' 1 -le 0 ']'
+ '[' centos == oracle ']'
+ '[' centos == centos ']'
+ version_ge 7 8
+ [[ 7 =~ 
 ]]
+ [[ 8 =~ 
 ]]
++ head -n 1
++ sort -rV
+ test 8 == 7
+ '[' -z Xray-REALITY+Web.sh ']'
+ [[ Xray-REALITY+Web.sh =~ ^/dev/fd/ ]]
+ '[' dnf == apt ']'
+ dnf mark install dnf
Traceback (most recent call last):
  File "/usr/bin/dnf", line 58, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 179, in user_main
    errcode = main(args)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 64, in main
    return _main(base, args, cli_class, option_parser_class)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 99, in _main
    return cli_run(cli, base)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 115, in cli_run
    cli.run()
  File "/usr/lib/python2.7/site-packages/dnf/cli/cli.py", line 1125, in run
    return self.command.run()
  File "/usr/lib/python2.7/site-packages/dnf/cli/commands/mark.py", line 89, in run
    rpmdb_version = self.sack._rpmdb_version()
AttributeError: 'MarkCommand' object has no attribute 'sack'
+ red '标记 dnf 手动安装失败！'
+ echo -e '\033[31;1m标记 dnf 手动安装失败！\033[0m'
标记 dnf 手动安装失败！
+ report_bug
+ green '欢迎进行Bug report(https://github.com/kirin10000/Xray-script/issues)，感谢您的支持'
+ echo -e '\033[32;1m欢迎进行Bug report(https://github.com/kirin10000/Xray-script/issues)，感谢您的支持\033[0m'
欢迎进行Bug report(https://github.com/kirin10000/Xray-script/issues)，感谢您的支持
+ yellow 按回车键继续或者Ctrl+c退出
+ echo -e '\033[33;1m按回车键继续或者Ctrl+c退出\033[0m'
按回车键继续或者Ctrl+c退出
+ read -rs

```

**Comment by megleo** [comment]
+1

**Comment by kirin10000** [comment]
这个尝试进行修复了
